#
# Based on subset of <https://github.com/NiklasEi/bevy_game_template/blob/main/.github/workflows/ci.yml>
#
# Added `ubuntu-18.04` for widest LTS version support (avoids libc version issues).
#
name: CI

on:
  pull_request:
  push:

  # Allows you to run this workflow manually from the Actions tab.
  # (via GitHub starter template)
  workflow_dispatch:

jobs:
  test:
    strategy:
      fail-fast: false    
      matrix:
        os: [ubuntu-18.04, ubuntu-latest, windows-latest, macos-latest]
    runs-on: ${{ matrix.os }}
    env:
      RUSTC_WRAPPER: "" # Workaround sccache not being installed.    
    steps:
      - uses: actions/checkout@v2
      - uses: actions/cache@v2
        with:
          path: |
            ~/.cargo/bin/
            ~/.cargo/registry/index/
            ~/.cargo/registry/cache/
            ~/.cargo/git/db/
            target/
          key: ${{ runner.os }}-cargo-build-nightly-${{ hashFiles('**/Cargo.toml') }}
      - uses: actions-rs/toolchain@v1
        with:
          toolchain: nightly
          override: true
      - name: Install alsa and udev
        run: sudo apt-get update; sudo apt-get install --no-install-recommends libasound2-dev libudev-dev
        if: runner.os == 'linux'
      - name: Build & run tests
        run: cargo test
      - name: Build (for artifact)
        run: cargo build
      - name: List files
        run: find .; find ~/.cargo; find ~/.rustup;
      - uses: actions/upload-artifact@v3
        with:
          name: ${{ runner.os }}-game-build-nightly-${{ hashFiles('**/Cargo.toml') }}-debug
          path: |
                target/debug/*dylib*
                target/debug/quacks*
                target/debug/libquacks*
                target/debug/deps/quacks*
                target/debug/deps/libquacks*
                ./target/debug/deps/bevy_dylib-328cd9fe55c06e85.d
                ./target/debug/deps/libbevy_dylib-328cd9fe55c06e85.so
                /home/runner/.rustup/toolchains/nightly-x86_64-unknown-linux-gnu/lib/libstd-91db243dd05c003b.so
                assets/
                /home/runner/.rustup/toolchains/nightly-x86_64-unknown-linux-gnu/lib/rustlib/x86_64-unknown-linux-gnu/lib/libstd*
                ~/.rustup/toolchains/*/lib/rustlib/*/*/libstd-* # Due to ??? (maybe same reason as below).
                target/debug/deps/libbevy_dylib* # Due to use of Bevy's dynamic library feature
